"""
Episodic Memory

Session summary generated by LLM, with pre-scored importance
to prevent critical decisions from being compressed away.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone
import asyncio


@dataclass
class SessionSummary:
    """Summary of a session"""
    summary: str
    key_points: List[str] = field(default_factory=list)
    tasks: List[str] = field(default_factory=list)
    decisions: List[str] = field(default_factory=list)
    updated_at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))


class EpisodicMemory:
    """Episodic memory - generates session summaries with importance scoring."""

    def __init__(
        self,
        update_interval: int = 5,
        max_summary_length: int = 500,
        max_messages: int = 200,
        ttl_seconds: float = 86400 * 7.0,  # 7 days default TTL
    ):
        self._update_interval = update_interval
        self._max_summary_length = max_summary_length
        self._max_messages = max_messages
        self._ttl_seconds = ttl_seconds
        self._summary = ""
        self._message_count = 0
        self._full_messages: List[Dict] = []
        self._critical_episodes: List[Dict] = []  # importance_score > 0.8
        self._scoring_enabled = True

    async def add_interaction(
        self,
        user_message: str,
        assistant_message: str,
        tool_calls: Optional[List[Dict]] = None,
        importance_score: float = 0.5,
        is_critical: bool = False,
    ):
        """Add an interaction to the session with auto-eviction.

        Args:
            importance_score: 0-1, pre-scored by background task.
                              > 0.8 = critical (promoted to Redis ZSET if available).
            is_critical: If True, signals that this interaction MUST be kept
                         through compression (used for HITL approvals, pipeline decisions).
        """
        entry = {
            "user": user_message,
            "assistant": assistant_message,
            "tool_calls": tool_calls or [],
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
            "importance_score": importance_score,
            "is_critical": is_critical,
        }
        self._full_messages.append(entry)
        self._message_count += 1

        # Critical episodes: never trimmed by normal compression
        if importance_score > 0.8 or is_critical:
            self._critical_episodes.append(entry)
            if len(self._critical_episodes) > 50:
                self._critical_episodes = self._critical_episodes[-50:]

        # Auto-evict: keep only the most recent max_messages
        if len(self._full_messages) > self._max_messages:
            self._full_messages = self._full_messages[-self._max_messages:]

    async def _score_interactions(self, llm_callable=None) -> None:
        """Background task: score recent un-scored interactions for importance.

        Called from save_interaction() as asyncio.create_task().
        Scores are persisted in the interaction dict, so compression can
        read them without any LLM latency.
        """
        if not llm_callable:
            return
        unscored = [m for m in self._full_messages
                     if m.get("importance_score", 0.5) == 0.5 and not m.get("is_critical")]
        if not unscored:
            return
        try:
            lines = []
            for i, m in enumerate(unscored[-5:]):
                lines.append(f"[{i}] User: {str(m.get('user', ''))[:200]}")
                lines.append(f"[{i}] Assistant: {str(m.get('assistant', ''))[:200]}")
            prompt = (
                "Score each interaction below for decision importance (0-1).\n"
                "> 0.8 = critical decision/pipeline output/approval result\n"
                "0.3-0.8 = regular work/status updates\n"
                "< 0.3 = casual chat/greetings/weather checks\n\n"
                + "\n".join(lines)
                + "\n\nReturn JSON array: [{\"i\": <index>, \"score\": <0-1>}, ...]"
            )
            response = await llm_callable(prompt)
            import json
            text = str(response) if not isinstance(response, dict) else json.dumps(response)
            start = text.find("[")
            end = text.rfind("]")
            if start >= 0 and end > start:
                scores = json.loads(text[start:end + 1])
                for entry in scores:
                    idx = entry.get("i", -1)
                    score = float(entry.get("score", 0.5))
                    if 0 <= idx < len(unscored):
                        unscored[idx]["importance_score"] = score
                        if score > 0.8:
                            self._critical_episodes.append(unscored[idx])
                            try:
                                from core.harness.memory.metrics import inc_critical_promoted
                                inc_critical_promoted()
                            except Exception:
                                pass
        except Exception:
            pass

    def get_critical_episodes(self, limit: int = 10) -> List[Dict]:
        """Get critical episodes for injection into context (never compressed)."""
        return self._critical_episodes[-limit:]
    
    async def should_update(self) -> bool:
        """Check if summary should be updated"""
        return self._message_count >= self._update_interval
    
    async def update_summary(self, llm_callable=None) -> SessionSummary:
        """Generate new summary using LLM (primary) or rule-based (fallback)."""
        if not self._full_messages:
            result = SessionSummary(summary="No interactions yet")
        elif llm_callable is not None:
            try:
                result = await self._llm_summary(llm_callable)
            except Exception:
                result = self._rule_summary()
        else:
            result = self._rule_summary()
        self._summary = result.summary
        self._message_count = 0
        return result

    async def _llm_summary(self, llm_callable) -> SessionSummary:
        recent = self._full_messages[-self._update_interval:]
        lines = []
        for m in recent:
            lines.append(f"User: {str(m.get('user', ''))[:300]}")
            lines.append(f"Assistant: {str(m.get('assistant', ''))[:300]}")
        from core.harness.utils.prompt_loader import _sync_resolve
        prompt = _sync_resolve("episodic-summary") + "\n\n" + chr(10).join(lines)
        response = await llm_callable(prompt)
        import json
        try:
            json_str = response
            if isinstance(response, dict):
                data = response
            else:
                # Try to extract JSON from response
                text = str(response)
                start = text.find("{")
                end = text.rfind("}")
                if start >= 0 and end > start:
                    data = json.loads(text[start:end + 1])
                else:
                    raise ValueError("No JSON found in LLM response")
            return SessionSummary(
                summary=str(data.get("summary", ""))[:self._max_summary_length],
                key_points=[str(p)[:200] for p in (data.get("key_points") or [])[:3]],
                tasks=[str(t)[:200] for t in (data.get("tasks") or [])[:3]],
                decisions=[str(d)[:200] for d in (data.get("decisions") or [])[:3]],
                updated_at=datetime.now(tz=timezone.utc),
            )
        except Exception:
            raise

    def _rule_summary(self) -> SessionSummary:
        user_messages = [m["user"] for m in self._full_messages[-self._update_interval:]]
        assistant_messages = [m["assistant"] for m in self._full_messages[-self._update_interval:]]

        summary_text = f"Session with {len(user_messages)} interactions. "
        if user_messages:
            summary_text += f"Last user query: {user_messages[-1][:100]}..."

        return SessionSummary(
            summary=summary_text[:self._max_summary_length],
            key_points=self._extract_key_points(assistant_messages),
            tasks=self._extract_tasks(user_messages),
            updated_at=datetime.now(tz=timezone.utc),
        )
    
    def get_summary(self) -> str:
        """Get current summary"""
        return self._summary
    
    def _extract_key_points(self, assistant_messages: List[str]) -> List[str]:
        """Extract key points from assistant responses"""
        points = []
        for msg in assistant_messages[-3:]:
            if "error" in msg.lower():
                points.append("Handled error situation")
            if "success" in msg.lower():
                points.append("Successfully completed task")
        return points[:3]
    
    def _extract_tasks(self, user_messages: List[str]) -> List[str]:
        """Extract tasks from user messages"""
        task_keywords = ["help", "do", "create", "fix", "write", "generate"]
        tasks = []
        for msg in user_messages:
            if any(kw in msg.lower() for kw in task_keywords):
                tasks.append(msg[:50])
        return tasks[:3]


__all__ = ["EpisodicMemory", "SessionSummary"]