"""
Episodic Memory

Session summary generated by LLM.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class SessionSummary:
    """Summary of a session"""
    summary: str
    key_points: List[str] = field(default_factory=list)
    tasks: List[str] = field(default_factory=list)
    decisions: List[str] = field(default_factory=list)
    updated_at: datetime = field(default_factory=datetime.utcnow)


class EpisodicMemory:
    """Episodic memory - generates session summaries"""
    
    def __init__(
        self,
        update_interval: int = 5,
        max_summary_length: int = 500
    ):
        self._update_interval = update_interval
        self._max_summary_length = max_summary_length
        self._summary = ""
        self._message_count = 0
        self._full_messages: List[Dict] = []
    
    async def add_interaction(
        self,
        user_message: str,
        assistant_message: str,
        tool_calls: Optional[List[Dict]] = None
    ):
        """Add an interaction to the session"""
        self._full_messages.append({
            "user": user_message,
            "assistant": assistant_message,
            "tool_calls": tool_calls or [],
            "timestamp": datetime.utcnow().isoformat()
        })
        self._message_count += 1
    
    async def should_update(self) -> bool:
        """Check if summary should be updated"""
        return self._message_count >= self._update_interval
    
    async def update_summary(self, llm_callable=None) -> SessionSummary:
        """Generate new summary using LLM"""
        # In real implementation, this would call the LLM
        # For now, create a basic summary
        
        if not self._full_messages:
            return SessionSummary(summary="No interactions yet")
        
        # Simple summary generation
        user_messages = [m["user"] for m in self._full_messages[-self._update_interval:]]
        assistant_messages = [m["assistant"] for m in self._full_messages[-self._update_interval:]]
        
        summary_text = f"Session with {len(user_messages)} interactions. "
        if user_messages:
            summary_text += f"Last user query: {user_messages[-1][:100]}..."
        
        new_summary = SessionSummary(
            summary=summary_text[:self._max_summary_length],
            key_points=self._extract_key_points(assistant_messages),
            tasks=self._extract_tasks(user_messages),
            updated_at=datetime.utcnow()
        )
        
        self._summary = new_summary.summary
        self._message_count = 0
        
        return new_summary
    
    def get_summary(self) -> str:
        """Get current summary"""
        return self._summary
    
    def _extract_key_points(self, assistant_messages: List[str]) -> List[str]:
        """Extract key points from assistant responses"""
        points = []
        for msg in assistant_messages[-3:]:
            if "error" in msg.lower():
                points.append("Handled error situation")
            if "success" in msg.lower():
                points.append("Successfully completed task")
        return points[:3]
    
    def _extract_tasks(self, user_messages: List[str]) -> List[str]:
        """Extract tasks from user messages"""
        task_keywords = ["help", "do", "create", "fix", "write", "generate"]
        tasks = []
        for msg in user_messages:
            if any(kw in msg.lower() for kw in task_keywords):
                tasks.append(msg[:50])
        return tasks[:3]


__all__ = ["EpisodicMemory", "SessionSummary"]