"""
Episodic Memory

Session summary generated by LLM.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class SessionSummary:
    """Summary of a session"""
    summary: str
    key_points: List[str] = field(default_factory=list)
    tasks: List[str] = field(default_factory=list)
    decisions: List[str] = field(default_factory=list)
    updated_at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))


class EpisodicMemory:
    """Episodic memory - generates session summaries"""
    
    def __init__(
        self,
        update_interval: int = 5,
        max_summary_length: int = 500,
        max_messages: int = 200,
        ttl_seconds: float = 86400 * 7.0,  # 7 days default TTL
    ):
        self._update_interval = update_interval
        self._max_summary_length = max_summary_length
        self._max_messages = max_messages
        self._ttl_seconds = ttl_seconds
        self._summary = ""
        self._message_count = 0
        self._full_messages: List[Dict] = []

    async def add_interaction(
        self,
        user_message: str,
        assistant_message: str,
        tool_calls: Optional[List[Dict]] = None
    ):
        """Add an interaction to the session with auto-eviction."""
        self._full_messages.append({
            "user": user_message,
            "assistant": assistant_message,
            "tool_calls": tool_calls or [],
            "timestamp": datetime.now(tz=timezone.utc).isoformat()
        })
        self._message_count += 1

        # Auto-evict: keep only the most recent max_messages
        if len(self._full_messages) > self._max_messages:
            self._full_messages = self._full_messages[-self._max_messages:]
    
    async def should_update(self) -> bool:
        """Check if summary should be updated"""
        return self._message_count >= self._update_interval
    
    async def update_summary(self, llm_callable=None) -> SessionSummary:
        """Generate new summary using LLM (primary) or rule-based (fallback)."""
        if not self._full_messages:
            result = SessionSummary(summary="No interactions yet")
        elif llm_callable is not None:
            try:
                result = await self._llm_summary(llm_callable)
            except Exception:
                result = self._rule_summary()
        else:
            result = self._rule_summary()
        self._summary = result.summary
        self._message_count = 0
        return result

    async def _llm_summary(self, llm_callable) -> SessionSummary:
        recent = self._full_messages[-self._update_interval:]
        lines = []
        for m in recent:
            lines.append(f"User: {str(m.get('user', ''))[:300]}")
            lines.append(f"Assistant: {str(m.get('assistant', ''))[:300]}")
        from core.harness.utils.prompt_loader import _sync_resolve
        prompt = _sync_resolve("episodic-summary") + "\n\n" + chr(10).join(lines)
        response = await llm_callable(prompt)
        import json
        try:
            json_str = response
            if isinstance(response, dict):
                data = response
            else:
                # Try to extract JSON from response
                text = str(response)
                start = text.find("{")
                end = text.rfind("}")
                if start >= 0 and end > start:
                    data = json.loads(text[start:end + 1])
                else:
                    raise ValueError("No JSON found in LLM response")
            return SessionSummary(
                summary=str(data.get("summary", ""))[:self._max_summary_length],
                key_points=[str(p)[:200] for p in (data.get("key_points") or [])[:3]],
                tasks=[str(t)[:200] for t in (data.get("tasks") or [])[:3]],
                decisions=[str(d)[:200] for d in (data.get("decisions") or [])[:3]],
                updated_at=datetime.now(tz=timezone.utc),
            )
        except Exception:
            raise

    def _rule_summary(self) -> SessionSummary:
        user_messages = [m["user"] for m in self._full_messages[-self._update_interval:]]
        assistant_messages = [m["assistant"] for m in self._full_messages[-self._update_interval:]]

        summary_text = f"Session with {len(user_messages)} interactions. "
        if user_messages:
            summary_text += f"Last user query: {user_messages[-1][:100]}..."

        return SessionSummary(
            summary=summary_text[:self._max_summary_length],
            key_points=self._extract_key_points(assistant_messages),
            tasks=self._extract_tasks(user_messages),
            updated_at=datetime.now(tz=timezone.utc),
        )
    
    def get_summary(self) -> str:
        """Get current summary"""
        return self._summary
    
    def _extract_key_points(self, assistant_messages: List[str]) -> List[str]:
        """Extract key points from assistant responses"""
        points = []
        for msg in assistant_messages[-3:]:
            if "error" in msg.lower():
                points.append("Handled error situation")
            if "success" in msg.lower():
                points.append("Successfully completed task")
        return points[:3]
    
    def _extract_tasks(self, user_messages: List[str]) -> List[str]:
        """Extract tasks from user messages"""
        task_keywords = ["help", "do", "create", "fix", "write", "generate"]
        tasks = []
        for msg in user_messages:
            if any(kw in msg.lower() for kw in task_keywords):
                tasks.append(msg[:50])
        return tasks[:3]


__all__ = ["EpisodicMemory", "SessionSummary"]