#!/bin/bash
# AUTO-GENERATED by scripts/generate_guard_rules.py
# SOURCE: architecture/boundary_rules.yaml
# GENERATED_AT: 2026-07-16T04:01:43Z
# SOURCE_HASH: 56239fb548c38494
# DO NOT EDIT — modify boundary_rules.yaml then re-run generate_guard_rules.py

set -euo pipefail
WORKSPACE="${WORKSPACE:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

echo "=== Architecture Guard: Boundary Rules ==="
echo ""

TOTAL_ERRORS=0
TOTAL_WARNINGS=0

# §1: ROUTE_PERMISSIONS must NOT appear in core/ (权限/路由/角色配置属于平台层唯一权威)
if grep -rw "ROUTE_PERMISSIONS" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ROUTE_PERMISSIONS found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层唯一权威"
  ((TOTAL_ERRORS++))
fi

# §2: SIDEBAR_MENUS must NOT appear in core/ (权限/路由/角色配置属于平台层唯一权威)
if grep -rw "SIDEBAR_MENUS" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: SIDEBAR_MENUS found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层唯一权威"
  ((TOTAL_ERRORS++))
fi

# §3: METHOD_RESTRICTIONS must NOT appear in core/ (权限/路由/角色配置属于平台层唯一权威)
if grep -rw "METHOD_RESTRICTIONS" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: METHOD_RESTRICTIONS found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层唯一权威"
  ((TOTAL_ERRORS++))
fi

# §4: SystemRole must NOT appear in core/ (权限/路由/角色配置属于平台层唯一权威)
if grep -rw "SystemRole" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: SystemRole found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层唯一权威"
  ((TOTAL_ERRORS++))
fi

# §5: ROUTE_PERMISSIONS must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "ROUTE_PERMISSIONS" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ROUTE_PERMISSIONS found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §6: SystemRole must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "SystemRole" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: SystemRole found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §7: ROUTE must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "ROUTE" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ROUTE found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §8: MENU must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "MENU" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: MENU found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §9: agent_name must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "agent_name" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: agent_name found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §10: business_role must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "business_role" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: business_role found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §11: customer_name must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "customer_name" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: customer_name found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §12: fde_ must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "fde_" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: fde_ found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §13: sys_llm_generate must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "sys_llm_generate" "$WORKSPACE/aiPlat-platform/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: sys_llm_generate found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §14: ReActLoop must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "ReActLoop" "$WORKSPACE/aiPlat-platform/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ReActLoop found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §15: PipelineEngine must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "PipelineEngine" "$WORKSPACE/aiPlat-platform/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: PipelineEngine found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §16: SkillRegistry must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "SkillRegistry" "$WORKSPACE/aiPlat-platform/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: SkillRegistry found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §17: model_registry must NOT appear in core/ (模型发现必须走 infra ModelManager (CLAUDE.md §5.31))
if grep -rw "model_registry" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: model_registry found in core/ (belongs to infra) — 模型发现必须走 infra ModelManager (CLAUDE.md §5.31)"
  ((TOTAL_ERRORS++))
fi

# §18: load_model must NOT appear in core/ (模型发现必须走 infra ModelManager (CLAUDE.md §5.31))
if grep -rw "load_model" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: load_model found in core/ (belongs to infra) — 模型发现必须走 infra ModelManager (CLAUDE.md §5.31)"
  ((TOTAL_ERRORS++))
fi

# Global rule §19: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0001.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0001.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §20: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0002.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0002.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §21: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0003.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0003.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §22: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0004.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0004.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §23: 配置驱动 (config_driven) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0005.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 配置驱动 (config_driven) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi

# Global rule §24: 配置驱动 (config_driven) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0006.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 配置驱动 (config_driven) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi

echo ""
echo "  TOTAL: $((TOTAL_ERRORS + TOTAL_WARNINGS)) issues ($TOTAL_ERRORS errors, $TOTAL_WARNINGS warnings)"
if [ "$TOTAL_ERRORS" -gt 0 ]; then
  echo "  Boundary violations found — fix before merging."
  exit 1
fi
echo "  Boundary check OK."