#!/bin/bash
# AUTO-GENERATED by scripts/generate_guard_rules.py
# SOURCE: architecture/boundary_rules.yaml
# GENERATED_AT: 2026-08-21T01:36:16Z
# SOURCE_HASH: f419f33a34589975
# DO NOT EDIT — modify boundary_rules.yaml then re-run generate_guard_rules.py

set -euo pipefail
WORKSPACE="${WORKSPACE:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

# v2.5 transitional: platform/apps/ contains copies from core — skip until migration complete
TRANSITIONAL_SKIP="--exclude-dir=apps"

echo "=== Architecture Guard: Boundary Rules ==="
echo ""

TOTAL_ERRORS=0
TOTAL_WARNINGS=0

# §1: ROUTE_PERMISSIONS must NOT appear in core/ (权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出)
if grep -rw "ROUTE_PERMISSIONS" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: ROUTE_PERMISSIONS found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出"
  ((TOTAL_WARNINGS++))
fi

# §2: SIDEBAR_MENUS must NOT appear in core/ (权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出)
if grep -rw "SIDEBAR_MENUS" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: SIDEBAR_MENUS found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出"
  ((TOTAL_WARNINGS++))
fi

# §3: METHOD_RESTRICTIONS must NOT appear in core/ (权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出)
if grep -rw "METHOD_RESTRICTIONS" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: METHOD_RESTRICTIONS found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出"
  ((TOTAL_WARNINGS++))
fi

# §4: SystemRole must NOT appear in core/ (权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出)
if grep -rw "SystemRole" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: SystemRole found in core/ (belongs to platform) — 权限/路由/角色配置属于平台层权威 — core仅允许兼容性重新导出"
  ((TOTAL_WARNINGS++))
fi

# §5: ROUTE_PERMISSIONS must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "ROUTE_PERMISSIONS" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ROUTE_PERMISSIONS found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §6: SystemRole must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "SystemRole" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: SystemRole found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §7: ROUTE must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "ROUTE" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ROUTE found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §8: MENU must NOT appear in infra/ (infra 完全独立，不含应用层概念)
if grep -rw "MENU" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: MENU found in infra/ (belongs to platform) — infra 完全独立，不含应用层概念"
  ((TOTAL_ERRORS++))
fi

# §9: agent_name must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "agent_name" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: agent_name found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §10: business_role must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "business_role" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: business_role found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §11: customer_name must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "customer_name" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: customer_name found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §12: fde_ must NOT appear in infra/ (infra 必须内核无关 (CLAUDE.md §5.29))
if grep -rw "fde_" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: fde_ found in infra/ (belongs to core) — infra 必须内核无关 (CLAUDE.md §5.29)"
  ((TOTAL_ERRORS++))
fi

# §13: sys_llm_generate must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "sys_llm_generate" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: sys_llm_generate found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §14: ReActLoop must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "ReActLoop" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: ReActLoop found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §15: PipelineEngine must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "PipelineEngine" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: PipelineEngine found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §16: SkillRegistry must NOT appear in platform/ (platform 不能直接访问 core 内部实现，必须通过 CoreFacade)
if grep -rw "SkillRegistry" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: SkillRegistry found in platform/ (belongs to core) — platform 不能直接访问 core 内部实现，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §17: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0001.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §18: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0002.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §19: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0003.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §20: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0004.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §21: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0005.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §22: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0006.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §23: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0007.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §24: regex pattern in platform/ (platform→core 内部导入 — 建议通过 CoreFacade (存量)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0008.txt" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in platform/ (belongs to core) — platform→core 内部导入 — 建议通过 CoreFacade (存量违规, Phase 3-4 逐步清理)"
  ((TOTAL_WARNINGS++))
fi

# §25: from core\.harness\.infrastructure\.crypto must NOT appear in platform/ (platform 直接访问 core harness 内部基础设施，必须通过 CoreFacade)
if grep -rw "from core\.harness\.infrastructure\.crypto" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: from core\.harness\.infrastructure\.crypto found in platform/ (belongs to core) — platform 直接访问 core harness 内部基础设施，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §26: from core\.harness\.kernel\.runtime must NOT appear in platform/ (platform 直接访问 core harness 内部基础设施，必须通过 CoreFacade)
if grep -rw "from core\.harness\.kernel\.runtime" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: from core\.harness\.kernel\.runtime found in platform/ (belongs to core) — platform 直接访问 core harness 内部基础设施，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §27: from core\.harness\.integration must NOT appear in platform/ (platform 直接访问 core harness 内部基础设施，必须通过 CoreFacade)
if grep -rw "from core\.harness\.integration" "$WORKSPACE/aiPlat-platform/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: from core\.harness\.integration found in platform/ (belongs to core) — platform 直接访问 core harness 内部基础设施，必须通过 CoreFacade"
  ((TOTAL_ERRORS++))
fi

# §28: model_registry must NOT appear in core/ (模型发现必须走 infra ModelManager (CLAUDE.md §5.31))
if grep -rw "model_registry" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: model_registry found in core/ (belongs to infra) — 模型发现必须走 infra ModelManager (CLAUDE.md §5.31)"
  ((TOTAL_ERRORS++))
fi

# §29: load_model must NOT appear in core/ (模型发现必须走 infra ModelManager (CLAUDE.md §5.31))
if grep -rw "load_model" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: load_model found in core/ (belongs to infra) — 模型发现必须走 infra ModelManager (CLAUDE.md §5.31)"
  ((TOTAL_ERRORS++))
fi

# §30: regex pattern in core/ (应用模块不应在 core/api/routers/ 下定义路由 — 应放在 pl)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0009.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  WARNING: pattern match in core/ (belongs to app-modules) — 应用模块不应在 core/api/routers/ 下定义路由 — 应放在 platform/apps/{module}"
  ((TOTAL_WARNINGS++))
fi

# Global rule §31: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0010.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0010.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §32: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0011.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0011.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §33: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0012.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0012.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §34: 内核无关 (kernel_agnostic) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0013.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0013.txt" "$WORKSPACE/aiPlat-infra/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 内核无关 (kernel_agnostic) — pattern match in aiPlat-infra/"
  ((TOTAL_ERRORS++))
fi

# Global rule §35: 配置驱动 (config_driven) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0014.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 配置驱动 (config_driven) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi

# Global rule §36: 配置驱动 (config_driven) (error)
if grep -rEf "$WORKSPACE/scripts/guard_patterns/pat_0015.txt" "$WORKSPACE/aiPlat-core/" --include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then
  echo "  ERROR: 配置驱动 (config_driven) — pattern match in aiPlat-core/"
  ((TOTAL_ERRORS++))
fi

echo ""
echo "  TOTAL: $((TOTAL_ERRORS + TOTAL_WARNINGS)) issues ($TOTAL_ERRORS errors, $TOTAL_WARNINGS warnings)"
if [ "$TOTAL_ERRORS" -gt 0 ]; then
  echo "  Boundary violations found — fix before merging."
  exit 1
fi
echo "  Boundary check OK."