#!/usr/bin/env python3
"""
Generate architecture guard rules from boundary_rules.yaml.

Reads architecture/boundary_rules.yaml and produces:
  1. scripts/architecture_guard_rules.sh  — generated grep rules (sourced by guard)
  2. scripts/guard_patterns/             — pattern files (used by the above)

The generated output is byte-identical (idempotent) when the YAML source
is unchanged, enabling pre-commit hook automatic sync detection.
"""
import hashlib
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
YAML_SRC = ROOT / "architecture" / "boundary_rules.yaml"
GUARD_OUT = ROOT / "scripts" / "architecture_guard_rules.sh"
PATTERN_DIR = ROOT / "scripts" / "guard_patterns"


def load_rules() -> Dict[str, Any]:
    with open(YAML_SRC) as fh:
        return yaml.safe_load(fh)


def gen_pattern_files(rules: Dict) -> Dict[str, str]:
    """Write all regex patterns to files. Returns {rule_id: filepath} map."""
    PATTERN_DIR.mkdir(exist_ok=True)
    pattern_files: Dict[str, str] = {}
    pid = 0
    
    for layer_name, layer in rules.get("layers", {}).items():
        for item in layer.get("forbidden_in", []):
            for pat in item.get("patterns", []):
                pid += 1
                fpath = PATTERN_DIR / f"pat_{pid:04d}.txt"
                fpath.write_text(pat + "\n")
                pattern_files[str(pid)] = str(fpath.relative_to(ROOT))
    
    for rule in rules.get("global_rules", []):
        for pat in rule.get("patterns", []):
            pid += 1
            fpath = PATTERN_DIR / f"pat_{pid:04d}.txt"
            fpath.write_text(pat + "\n")
            pattern_files[str(pid)] = str(fpath.relative_to(ROOT))
    
    return pattern_files


def gen_guard_script(rules: Dict, pattern_files: Dict[str, str]) -> str:
    """Generate bash grep-rules script."""
    yaml_hash = hashlib.sha256(YAML_SRC.read_bytes()).hexdigest()[:16]
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    
    lines = [
        "#!/bin/bash",
        f"# AUTO-GENERATED by scripts/generate_guard_rules.py",
        f"# SOURCE: architecture/boundary_rules.yaml",
        f"# GENERATED_AT: {ts}",
        f"# SOURCE_HASH: {yaml_hash}",
        f"# DO NOT EDIT — modify {YAML_SRC.name} then re-run generate_guard_rules.py",
        "",
        "set -euo pipefail",
        'WORKSPACE="${WORKSPACE:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"',
        "",
        "# v2.5 transitional: platform/apps/ contains copies from core — skip until migration complete",
        'TRANSITIONAL_SKIP="--exclude-dir=apps"',
        "",
        'echo "=== Architecture Guard: Boundary Rules ==="',
        'echo ""',
        "",
        'TOTAL_ERRORS=0',
        'TOTAL_WARNINGS=0',
    ]
    
    rule_id = 0
    pid = 0
    
    # Per-layer forbidden-in rules
    for layer_name, layer in rules.get("layers", {}).items():
        forbidden = layer.get("forbidden_in", [])
        for item in forbidden:
            target = item.get("layer", "")
            reason = item.get("reason", "")
            severity = item.get("severity", "warning")
            
            sev_var = "TOTAL_ERRORS" if severity == "error" else "TOTAL_WARNINGS"
            label = "ERROR" if severity == "error" else "WARNING"
            
            # symbols (exact word match)
            for sym in item.get("symbols", []):
                rule_id += 1
                dirs = _layer_to_dirs(target)
                lines.append("")
                lines.append(f'# §{rule_id}: {sym} must NOT appear in {target}/ ({reason[:50]})')
                for d in dirs:
                    lines.append(
                        f'if grep -rw "{sym}" "$WORKSPACE/{d}/" '
                        f'--include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then\n'
                        f'  echo "  {label}: {sym} found in {target}/ (belongs to {layer_name}) — {reason[:80]}"\n'
                        f'  (({sev_var}++))\n'
                        f'fi'
                    )
            
            # patterns (regex via pre-generated pattern files)
            for pat in item.get("patterns", []):
                pid += 1
                rule_id += 1
                pf = pattern_files.get(str(pid), "")
                dirs = _layer_to_dirs(target)
                lines.append("")
                lines.append(f'# §{rule_id}: regex pattern in {target}/ ({reason[:40]})')
                for d in dirs:
                    lines.append(
                        f'if grep -rEf "$WORKSPACE/{pf}" "$WORKSPACE/{d}/" '
                        f'--include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then\n'
                        f'  echo "  {label}: pattern match in {target}/ (belongs to {layer_name}) — {reason[:60]}"\n'
                        f'  (({sev_var}++))\n'
                        f'fi'
                    )
    
    # Global rules
    for rule in rules.get("global_rules", []):
        applies = rule.get("applies_to", [])
        severity = rule.get("severity", "warning")
        sev_var = "TOTAL_ERRORS" if severity == "error" else "TOTAL_WARNINGS"
        label = "ERROR" if severity == "error" else "WARNING"
        
        for pat in rule.get("patterns", []):
            pid += 1
            rule_id += 1
            pf = pattern_files.get(str(pid), "")
            dirs = [_layer_to_dirs(l) for l in applies]
            dirs_flat = [d for sublist in dirs for d in sublist]
            lines.append("")
            lines.append(f'# Global rule §{rule_id}: {rule["name"]} ({severity})')
            for d in dirs_flat:
                lines.append(
                    f'if grep -rEf "$WORKSPACE/{pf}" "$WORKSPACE/{d}/" '
                    f'--include="*.py" $TRANSITIONAL_SKIP 2>/dev/null | grep -v "# noqa: boundary" | grep -q .; then\n'
                    f'  echo "  {label}: {rule["name"]} — pattern match in {d}/"\n'
                    f'  (({sev_var}++))\n'
                    f'fi'
                )
    
    lines.append("")
    lines.append('echo ""')
    lines.append('echo "  TOTAL: $((TOTAL_ERRORS + TOTAL_WARNINGS)) issues '
                 '($TOTAL_ERRORS errors, $TOTAL_WARNINGS warnings)"')
    lines.append('if [ "$TOTAL_ERRORS" -gt 0 ]; then')
    lines.append('  echo "  Boundary violations found — fix before merging."')
    lines.append('  exit 1')
    lines.append('fi')
    lines.append('echo "  Boundary check OK."')
    
    return "\n".join(lines)


def _layer_to_dirs(layer: str) -> List[str]:
    mapping = {
        "core":    ["aiPlat-core"],
        "platform":["aiPlat-platform"],
        "infra":   ["aiPlat-infra"],
        "management": ["aiPlat-management"],
    }
    return mapping.get(layer, [])


def main():
    rules = load_rules()
    
    # 1. Write pattern files
    pattern_files = gen_pattern_files(rules)
    print(f"Generated {len(pattern_files)} pattern files in {PATTERN_DIR}")
    
    # 2. Generate guard script
    guard_script = gen_guard_script(rules, pattern_files)
    GUARD_OUT.write_text(guard_script)
    GUARD_OUT.chmod(0o755)
    print(f"Generated: {GUARD_OUT} ({len(guard_script.splitlines())} lines)")
    
    # 3. Idempotency check
    guard_script2 = gen_guard_script(rules, pattern_files)
    if guard_script != guard_script2:
        print("ERROR: guard script is NOT idempotent")
        sys.exit(1)
    print("Idempotency check: PASS")


if __name__ == "__main__":
    main()
