"""

Phase 28: GoalGenerator — autonomous improvement proposal engine.



Scans system state across all Phases (24-27) to identify actionable

improvement opportunities. Generates structured proposals with

priority, estimated impact, and auto-execution capability.



L5 capability: the system can propose what to work on, not just

execute given tasks. This is the final piece of the self-evolution puzzle.



    Scan areas:

       1. Healing gaps — cold-start error types with no strategy data

       2. Strategy optimization — low-success strategies needing replacement

       3. Knowledge staleness — shared facts older than threshold

       4. Snapshot trends — pipeline degradation over time

       5. Exploration gaps — untried strategies for active error types

       6. Tool gaps — capability gaps fillable by ToolBootstrapEngine

       7. Doc health — oversized documentation files

       8. Domain feedback — unresolved client field findings

       9. Business objectives — abstract goals decomposed via AbstractGoalDecomposer (Phase 39)

    """



from __future__ import annotations



import logging

import time

from dataclasses import dataclass, field, asdict

from enum import Enum

from typing import Any, Dict, List, Optional



logger = logging.getLogger("aiplat.goal_generator")





class GoalType(Enum):

    HEALING_GAP = "healing_gap"

    STRATEGY_OPTIMIZE = "strategy_optimize"

    KNOWLEDGE_STALE = "knowledge_stale"

    SNAPSHOT_DEGRADATION = "snapshot_degradation"

    EXPLORATION_GAP = "exploration_gap"

    TOOL_GAP = "tool_gap"

    DOC_HEALTH = "doc_health"

    DOMAIN_FEEDBACK = "domain_feedback"  # renamed from FDE_FEEDBACK — domain-agnostic

    BUSINESS_OBJECTIVE = "business_objective"  # Phase 39: decomposed from abstract goal





class Priority(Enum):

    CRITICAL = 4  # immediate action needed

    HIGH = 3

    MEDIUM = 2

    LOW = 1





@dataclass

class Goal:

    """A structured improvement proposal generated by the system."""



    goal_id: str

    title: str

    description: str

    goal_type: GoalType

    priority: Priority

    estimated_impact: str  # human-readable impact estimate

    auto_executable: bool = False  # can the system try this automatically?

    suggested_action: str = ""  # what to do

    source_evidence: Dict[str, Any] = field(default_factory=dict)

    generated_at: float = field(default_factory=time.time)



    def to_dict(self) -> Dict[str, Any]:

        d = asdict(self)

        d["goal_type"] = self.goal_type.value

        d["priority"] = self.priority.value

        return d





class GoalGenerator:

    """Scans system state and generates actionable improvement proposals.



    Usage:

        gen = GoalGenerator()

        goals = gen.generate()

        for g in goals:

            print(f"[{g.priority.name}] {g.title}: {g.description}")

    """



    def generate(self) -> List[Goal]:

        """Run all scanners and return consolidated goal list."""

        goals: List[Goal] = []

        goals.extend(self._scan_healing_gaps())

        goals.extend(self._scan_strategy_optimization())

        goals.extend(self._scan_knowledge_staleness())

        goals.extend(self._scan_exploration_gaps())

        goals.extend(self._scan_tool_gaps())

        goals.extend(self._scan_doc_health())

        goals.extend(self._scan_domain_feedback())

        goals.extend(self._scan_business_objectives())

        goals.sort(key=lambda g: (g.priority.value, -g.generated_at), reverse=True)

        return goals



    def generate_auto_executable(self) -> List[Goal]:

        """Return only goals that can be auto-executed (no human approval needed)."""

        return [g for g in self.generate() if g.auto_executable]



    # ── Scanners ──



    def _scan_healing_gaps(self) -> List[Goal]:

        """Scan for error types that have never had any strategy tried."""

        try:

            from core.harness.optimization.strategy_tracker import get_strategy_tracker

            tracker = get_strategy_tracker()

            known_reasons = {

                "rate_limit", "auth", "auth_permanent", "billing",

                "timeout", "overloaded", "server_error",

                "context_overflow", "payload_too_large",

                "model_not_found", "format_error", "param_out_of_range",

                "thinking_signature", "long_context_tier",

            }

            goals = []

            for reason in known_reasons:

                if tracker.is_cold_start(reason):

                    best = tracker.explore_strategy(reason)

                    goals.append(Goal(

                        goal_id=f"heal-gap-{reason}",

                        title=f"Establish healing strategy for '{reason}'",

                        description=f"Error type '{reason}' has no strategy history. "

                                     f"First untried strategy: {best or 'all tried'}.",

                        goal_type=GoalType.HEALING_GAP,

                        priority=Priority.MEDIUM,

                        estimated_impact="Reduces system downtime for this error class",

                        auto_executable=False,

                        suggested_action=f"Trigger test pipeline with simulated {reason} error",

                        source_evidence={"error_type": reason, "cold_start": True},

                    ))

            return goals

        except Exception as e:

            logger.debug("healing gap scan skipped: %s", e)

            return []



    def _scan_strategy_optimization(self) -> List[Goal]:

        """Scan for strategies with low success rate that could be optimized."""

        try:

            from core.harness.optimization.strategy_tracker import get_strategy_tracker

            tracker = get_strategy_tracker()

            ranked_sets = {}

            for (error_type, strategy), rec in tracker._records.items():

                if rec.attempts >= 3 and rec.success_rate < 0.5 and rec.success_rate > 0:

                    ranked_sets.setdefault(error_type, []).append(

                        (strategy, rec.success_rate, rec.attempts)

                    )



            goals = []

            for error_type, strategies in ranked_sets.items():

                for strategy, rate, attempts in strategies:

                    goals.append(Goal(

                        goal_id=f"strat-opt-{error_type}-{strategy}",

                        title=f"Replace '{strategy}' for '{error_type}'",

                        description=f"Strategy '{strategy}' has only {rate:.0%} success "

                                     f"({attempts} attempts). Try alternative strategies.",

                        goal_type=GoalType.STRATEGY_OPTIMIZE,

                        priority=Priority.HIGH if rate < 0.3 else Priority.MEDIUM,

                        estimated_impact="Improves self-healing success rate",

                        auto_executable=True,

                        suggested_action=f"Use tracker to select better strategy for {error_type}",

                        source_evidence={

                            "error_type": error_type,

                            "strategy": strategy,

                            "success_rate": round(rate, 3),

                            "attempts": attempts,

                        },

                    ))

            return goals

        except Exception as e:

            logger.debug("strategy optimization scan skipped: %s", e)

            return []



    def _scan_knowledge_staleness(self) -> List[Goal]:

        """Scan for shared knowledge facts older than 7 days."""

        try:

            from core.harness.memory.shared_pool import get_shared_knowledge_pool

            pool = get_shared_knowledge_pool()

            threshold = time.time() - 7 * 86400

            stale = [

                f for f in pool.query_all(limit=50)

                if f.timestamp < threshold

            ]

            goals = []

            if len(stale) >= 5:

                goals.append(Goal(

                    goal_id="knowledge-stale",

                    title=f"Refresh {len(stale)} stale shared knowledge facts",

                    description=f"{len(stale)} facts in shared pool are older than 7 days. "

                                 "Consider re-validating or removing them.",

                    goal_type=GoalType.KNOWLEDGE_STALE,

                    priority=Priority.LOW,

                    estimated_impact="Keeps shared knowledge fresh and relevant",

                    auto_executable=False,

                    suggested_action="Run re-validation pipeline on stale facts",

                    source_evidence={"stale_count": len(stale), "threshold_days": 7},

                ))

                # Trigger knowledge refresh pipeline

                try:

                    from core.harness.ontology_engine.engine import trigger_pipeline

                    import asyncio

                    asyncio.create_task(trigger_pipeline("knowledge_refresh", {

                        "stale_count": len(stale),

                        "threshold_days": 7,

                    }))

                except Exception:

                    logging.getLogger(__name__).debug('_scan_knowledge_staleness failed', exc_info=True)
            return goals

        except Exception as e:

            logger.debug("knowledge staleness scan skipped: %s", e)

            return []



    def _scan_exploration_gaps(self) -> List[Goal]:

        """Scan for error types that are active but have untried strategies."""

        try:

            from core.harness.optimization.strategy_tracker import get_strategy_tracker

            tracker = get_strategy_tracker()

            goals = []

            for (error_type, strategy), rec in tracker._records.items():

                if rec.attempts >= 5 and rec.success_rate > 0.7:

                    # This strategy works well — check if there are unexplored alternatives

                    explore = tracker.explore_strategy(error_type)

                    if explore:

                        goals.append(Goal(

                            goal_id=f"explore-{error_type}-{explore}",

                            title=f"Explore alternative: '{explore}' for '{error_type}'",

                            description=f"Current best strategy has {rec.success_rate:.0%} "

                                         f"success. Untried '{explore}' may be even better.",

                            goal_type=GoalType.EXPLORATION_GAP,

                            priority=Priority.LOW,

                            estimated_impact="Potentially improves healing by discovering better strategies",

                            auto_executable=True,

                            suggested_action=f"Allow tracker to try '{explore}' next time",

                            source_evidence={

                                "error_type": error_type,

                                "current_best": strategy,

                                "untried": explore,

                            },

                        ))

            return goals

        except Exception as e:

            logger.debug("exploration gap scan skipped: %s", e)

            return []



    def _scan_tool_gaps(self) -> List[Goal]:

        """Phase 31: Scan for capability gaps that could be filled by bootstrapping tools."""

        try:

            from core.harness.memory.shared_pool import get_shared_knowledge_pool

            pool = get_shared_knowledge_pool()

            # Check for error patterns that recur but have no dedicated tool

            error_facts = pool.query("error", limit=10, min_confidence=0.5)

            error_types = set()

            for f in error_facts:

                meta = f.metadata

                if isinstance(meta, dict) and "error_type" in meta:

                    error_types.add(meta["error_type"])



            goals = []

            # If we have multiple error types but no bootstrap tools

            try:

                from core.harness.optimization.tool_bootstrap import ToolBootstrapEngine

                import os as _os

                bootstrap_dir = ToolBootstrapEngine.SKILLS_DIR

                existing = len([f for f in _os.listdir(bootstrap_dir)

                                if _os.path.isdir(_os.path.join(bootstrap_dir, f))

                                and not f.startswith("_")]) if _os.path.isdir(bootstrap_dir) else 0

            except Exception:

                existing = 0



            if len(error_types) >= 3 and existing == 0:

                goals.append(Goal(

                    goal_id="tool-gap-bootstrap",

                    title="Bootstrap initial set of diagnostic tools",

                    description=f"{len(error_types)} error types detected with no dedicated tools. "

                                 "Consider bootstrapping diagnostic tools for common errors.",

                    goal_type=GoalType.TOOL_GAP,

                    priority=Priority.MEDIUM,

                    estimated_impact="Increases system resilience with dedicated diagnostic tools",

                    auto_executable=True,

                    suggested_action="Run ToolBootstrapEngine for top error types",

                    source_evidence={"error_types": list(error_types)[:5], "existing_tools": existing},

                ))



            # Scan for high-frequency queries without matching skills

            try:

                from core.harness.optimization.strategy_tracker import get_strategy_tracker

                tracker = get_strategy_tracker()

                high_freq = []

                for (error_type, strategy), rec in tracker._records.items():

                    if rec.attempts >= 10:

                        high_freq.append(error_type)

                # If there's a recurring pattern with no bootstrap skill

                for et in set(high_freq):

                    skill_path = os.path.join(

                        os.path.expanduser("~/.aiplat/skills/bootstrap"),

                        f"{et.replace(' ', '_')}/SKILL.md"

                    )

                    if not os.path.exists(skill_path):

                        goals.append(Goal(

                            goal_id=f"tool-gap-{et}",

                            title=f"Bootstrap tool for '{et}' problems",

                            description=f"Error type '{et}' occurs frequently ({tracker._records[(et, list(tracker._records.keys())[0][1] if tracker._records else 'unknown')].attempts if tracker._records else 0}x). "

                                         "Consider auto-bootstrapping a diagnostic Skill.",

                            goal_type=GoalType.TOOL_GAP,

                            priority=Priority.MEDIUM,

                            estimated_impact="Provides automated diagnostics for recurring error patterns",

                            auto_executable=True,

                            suggested_action=f"Auto-bootstrap tool: {et}_diagnostics",

                            source_evidence={"error_type": et, "frequency": "high"},

                        ))

            except Exception:

                logging.getLogger(__name__).debug('_scan_tool_gaps failed', exc_info=True)


            return goals

        except Exception as e:

            logger.debug("tool gap scan skipped: %s", e)

            return []



    def _scan_doc_health(self) -> List[Goal]:

        """Deterministic documentation-health monitor (doc governance stage 2).



        Watches for the "只加不减" regression the doc-slimming cleanup fixed:

          - CLAUDE.md creeping back over its budget

          - any Markdown file growing oversized (>500 lines)

        All doc goals are human-approved (auto_executable=False) — doc edits

        must not be auto-applied. Cheap, LLM-free indicators only.

        """

        try:

            import os

            from pathlib import Path



            here = Path(__file__).resolve()

            core_root = here.parents[3]        # aiPlat-core/

            workspace = here.parents[4]        # repo root

            claude_md = core_root / "CLAUDE.md"



            goals: List[Goal] = []



            # Indicator 1: CLAUDE.md size budget (rules-only doc should stay lean)

            claude_budget = int(os.getenv("AIPLAT_CLAUDE_MD_MAX_LINES", "2000"))

            if claude_md.exists():

                claude_lines = sum(1 for _ in claude_md.open(encoding="utf-8", errors="ignore"))

                if claude_lines > claude_budget:

                    goals.append(Goal(

                        goal_id="doc-health-claude-oversized",

                        title=f"CLAUDE.md 超预算 ({claude_lines} > {claude_budget} 行)",

                        description="CLAUDE.md 应聚焦耐久规则；状态快照迁往 docs/PHASE_STATUS.md。"

                                     "运行 scripts/extract_status_sections.py 生成瘦身草稿。",

                        goal_type=GoalType.DOC_HEALTH,

                        priority=Priority.MEDIUM,

                        estimated_impact="降低 CLAUDE.md 上下文注入成本，防止规则被状态淹没",

                        auto_executable=False,

                        suggested_action="python3 scripts/extract_status_sections.py（人工审阅 diff 后应用）",

                        source_evidence={"file": "aiPlat-core/CLAUDE.md",

                                          "lines": claude_lines, "budget": claude_budget},

                    ))



            # Indicator 2: oversized Markdown files (>500 lines)

            oversized_limit = int(os.getenv("AIPLAT_MD_MAX_LINES", "500"))

            skip_dirs = {"node_modules", ".venv", ".git", "__pycache__", "download", "archive"}

            oversized: List[Dict[str, Any]] = []

            for root, dirs, files in os.walk(workspace):

                dirs[:] = [d for d in dirs if d not in skip_dirs]

                for fn in files:

                    if not fn.endswith(".md"):

                        continue

                    fp = os.path.join(root, fn)

                    try:

                        with open(fp, encoding="utf-8", errors="ignore") as f:

                            n = sum(1 for _ in f)

                    except Exception:

                        continue

                    if n > oversized_limit:

                        oversized.append({"file": os.path.relpath(fp, workspace), "lines": n})

            if len(oversized) >= 5:

                oversized.sort(key=lambda x: x["lines"], reverse=True)

                goals.append(Goal(

                    goal_id="doc-health-oversized-md",

                    title=f"{len(oversized)} 个 Markdown 文件超 {oversized_limit} 行",

                    description="过大文档降低可维护性；考虑拆分或用指针替换正文。"

                                 f"最大：{', '.join(o['file'] for o in oversized[:3])}",

                    goal_type=GoalType.DOC_HEALTH,

                    priority=Priority.LOW,

                    estimated_impact="提升文档可维护性，抑制文档沙堆增长",

                    auto_executable=False,

                    suggested_action="拆分或归档 top 超大文档（人工）",

                    source_evidence={"oversized_count": len(oversized),

                                     "limit": oversized_limit, "top": oversized[:5]},

                ))

            return goals

        except Exception as e:

            logger.debug("doc health scan skipped: %s", e)

            return []



    def _scan_domain_feedback(self) -> List[Goal]:

        """Domain feedback → generate improvement proposals.



        Scans ~/.aiplat/field_feedback/*.json and generates a Goal for each

        unresolved feedback entry, enabling field findings to drive product

        iteration through the GoalGenerator → GoalExecutor → Repair Center loop.

        """

        try:

            from core.feedback.field_feedback import list_field_feedback

            unresolved = [fb for fb in list_field_feedback(limit=50)

                          if fb.get("status") != "resolved"]

            goals: List[Goal] = []

            for fb in unresolved[:10]:

                improvement = fb.get("suggested_improvement", {}) or {}

                priority = (

                    Priority.HIGH if improvement.get("priority") in ("high", "critical")

                    else Priority.MEDIUM

                )

                goals.append(Goal(

                    goal_id=f"fde-{fb.get('id','unknown')}",

                    title=f"FDE反馈: {fb.get('issue',{}).get('description','')[:60]}",

                    description="客户现场发现的问题, 应由总部团队审查并纳入产品迭代。",

                    goal_type=GoalType.DOMAIN_FEEDBACK,

                    priority=priority,

                    estimated_impact=f"客户: {fb.get('customer_profile_id','')} | "

                                     f"组件: {fb.get('issue',{}).get('affected_component','')}",

                    auto_executable=False,

                    suggested_action="Review FDE feedback, incorporate into product roadmap",

                    source_evidence={"feedback_id": fb.get("id", ""),

                                     "customer": fb.get("customer_profile_id", "")},

                ))

            return goals

        except Exception as e:

            logger.debug("FDE feedback scan skipped: %s", e)

            return []



    def _scan_business_objectives(self) -> List[Goal]:

        """Phase 39: Load pending abstract goals from disk for async decomposition.



        Reads ~/.aiplat/goals/pending/*.json and returns their raw Goal entries.

        The actual LLM decomposition runs in GoalExecutor._scan_and_execute()

        (async context) via _decompose_pending_objectives().

        """

        try:

            import json as _json_module

            import os as _os_module

            pending_dir = _os_module.path.expanduser("~/.aiplat/goals/pending")

            if not _os_module.path.isdir(pending_dir):

                return []

            from core.harness.optimization.abstract_goal_decomposer import get_abstract_goal_decomposer

            decomposer = get_abstract_goal_decomposer()

            if not decomposer.enabled:

                return []

        except Exception as e:

            logger.debug("business objectives scan: decomposer unavailable: %s", e)

            return []



        goals: List[Goal] = []

        try:

            entries = sorted(

                _os_module.listdir(pending_dir),

                key=lambda n: _os_module.path.getmtime(

                    _os_module.path.join(pending_dir, n)

                ),

            )

        except Exception:

            return goals



        for entry in entries[:3]:

            if not entry.endswith(".json"):

                continue

            fp = _os_module.path.join(pending_dir, entry)

            try:

                with open(fp, encoding="utf-8") as f:

                    obj = _json_module.load(f)

            except Exception:

                continue

            if not isinstance(obj, dict):

                continue

            text = obj.get("text", "")

            if not text:

                continue

            goals.append(Goal(

                goal_id=f"bizobj-{entry.replace('.json','')[:20]}",

                title=f"抽象目标: {text[:60]}",

                description=f"待分解的模糊业务目标。原始: {text[:120]}",

                goal_type=GoalType.BUSINESS_OBJECTIVE,

                priority=Priority.HIGH,

                estimated_impact=f"待 AbstractGoalDecomposer 分解",

                auto_executable=True,

                suggested_action="GoalExecutor 将在异步上下文中调用 AbstractGoalDecomposer.decompose()",

                source_evidence={

                    "abstract_goal_text": text,

                    "domain_id": obj.get("domain_id", ""),

                    "pending_file": entry,

                },

                generated_at=obj.get("submitted_at", _time),

            ))

        return goals



    def stats(self) -> Dict[str, Any]:

        """Generate summary stats."""

        goals = self.generate()

        return {

            "total_goals": len(goals),

            "by_type": {t.value: sum(1 for g in goals if g.goal_type.value == t.value) for t in GoalType},

            "by_priority": {p.name: sum(1 for g in goals if g.priority == p) for p in Priority},

            "auto_executable": sum(1 for g in goals if g.auto_executable),

            "top_goal": goals[0].to_dict() if goals else None,

        }





# ── Process-wide singleton ──



_generator: Optional[GoalGenerator] = None





def get_goal_generator() -> GoalGenerator:

    global _generator

    if _generator is None:

        _generator = GoalGenerator()

    return _generator

