"""
Phase 28: GoalGenerator — autonomous improvement proposal engine.

Scans system state across all Phases (24-27) to identify actionable
improvement opportunities. Generates structured proposals with
priority, estimated impact, and auto-execution capability.

L5 capability: the system can propose what to work on, not just
execute given tasks. This is the final piece of the self-evolution puzzle.

Scan areas:
  1. Healing gaps — cold-start error types with no strategy data
  2. Strategy optimization — low-success strategies needing replacement
  3. Knowledge staleness — shared facts older than threshold
  4. Snapshot trends — pipeline degradation over time
  5. Exploration gaps — untried strategies for active error types
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger("aiplat.goal_generator")


class GoalType(Enum):
    HEALING_GAP = "healing_gap"
    STRATEGY_OPTIMIZE = "strategy_optimize"
    KNOWLEDGE_STALE = "knowledge_stale"
    SNAPSHOT_DEGRADATION = "snapshot_degradation"
    EXPLORATION_GAP = "exploration_gap"


class Priority(Enum):
    CRITICAL = 4  # immediate action needed
    HIGH = 3
    MEDIUM = 2
    LOW = 1


@dataclass
class Goal:
    """A structured improvement proposal generated by the system."""

    goal_id: str
    title: str
    description: str
    goal_type: GoalType
    priority: Priority
    estimated_impact: str  # human-readable impact estimate
    auto_executable: bool = False  # can the system try this automatically?
    suggested_action: str = ""  # what to do
    source_evidence: Dict[str, Any] = field(default_factory=dict)
    generated_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["goal_type"] = self.goal_type.value
        d["priority"] = self.priority.value
        return d


class GoalGenerator:
    """Scans system state and generates actionable improvement proposals.

    Usage:
        gen = GoalGenerator()
        goals = gen.generate()
        for g in goals:
            print(f"[{g.priority.name}] {g.title}: {g.description}")
    """

    def generate(self) -> List[Goal]:
        """Run all scanners and return consolidated goal list."""
        goals: List[Goal] = []
        goals.extend(self._scan_healing_gaps())
        goals.extend(self._scan_strategy_optimization())
        goals.extend(self._scan_knowledge_staleness())
        goals.extend(self._scan_exploration_gaps())
        goals.sort(key=lambda g: (g.priority.value, -g.generated_at), reverse=True)
        return goals

    def generate_auto_executable(self) -> List[Goal]:
        """Return only goals that can be auto-executed (no human approval needed)."""
        return [g for g in self.generate() if g.auto_executable]

    # ── Scanners ──

    def _scan_healing_gaps(self) -> List[Goal]:
        """Scan for error types that have never had any strategy tried."""
        try:
            from core.harness.optimization.strategy_tracker import get_strategy_tracker
            tracker = get_strategy_tracker()
            known_reasons = {
                "rate_limit", "auth", "auth_permanent", "billing",
                "timeout", "overloaded", "server_error",
                "context_overflow", "payload_too_large",
                "model_not_found", "format_error", "param_out_of_range",
                "thinking_signature", "long_context_tier",
            }
            goals = []
            for reason in known_reasons:
                if tracker.is_cold_start(reason):
                    best = tracker.explore_strategy(reason)
                    goals.append(Goal(
                        goal_id=f"heal-gap-{reason}",
                        title=f"Establish healing strategy for '{reason}'",
                        description=f"Error type '{reason}' has no strategy history. "
                                     f"First untried strategy: {best or 'all tried'}.",
                        goal_type=GoalType.HEALING_GAP,
                        priority=Priority.MEDIUM,
                        estimated_impact="Reduces system downtime for this error class",
                        auto_executable=False,
                        suggested_action=f"Trigger test pipeline with simulated {reason} error",
                        source_evidence={"error_type": reason, "cold_start": True},
                    ))
            return goals
        except Exception as e:
            logger.debug("healing gap scan skipped: %s", e)
            return []

    def _scan_strategy_optimization(self) -> List[Goal]:
        """Scan for strategies with low success rate that could be optimized."""
        try:
            from core.harness.optimization.strategy_tracker import get_strategy_tracker
            tracker = get_strategy_tracker()
            ranked_sets = {}
            for (error_type, strategy), rec in tracker._records.items():
                if rec.attempts >= 3 and rec.success_rate < 0.5 and rec.success_rate > 0:
                    ranked_sets.setdefault(error_type, []).append(
                        (strategy, rec.success_rate, rec.attempts)
                    )

            goals = []
            for error_type, strategies in ranked_sets.items():
                for strategy, rate, attempts in strategies:
                    goals.append(Goal(
                        goal_id=f"strat-opt-{error_type}-{strategy}",
                        title=f"Replace '{strategy}' for '{error_type}'",
                        description=f"Strategy '{strategy}' has only {rate:.0%} success "
                                     f"({attempts} attempts). Try alternative strategies.",
                        goal_type=GoalType.STRATEGY_OPTIMIZE,
                        priority=Priority.HIGH if rate < 0.3 else Priority.MEDIUM,
                        estimated_impact="Improves self-healing success rate",
                        auto_executable=True,
                        suggested_action=f"Use tracker to select better strategy for {error_type}",
                        source_evidence={
                            "error_type": error_type,
                            "strategy": strategy,
                            "success_rate": round(rate, 3),
                            "attempts": attempts,
                        },
                    ))
            return goals
        except Exception as e:
            logger.debug("strategy optimization scan skipped: %s", e)
            return []

    def _scan_knowledge_staleness(self) -> List[Goal]:
        """Scan for shared knowledge facts older than 7 days."""
        try:
            from core.harness.memory.shared_pool import get_shared_knowledge_pool
            pool = get_shared_knowledge_pool()
            threshold = time.time() - 7 * 86400
            stale = [
                f for f in pool.query_all(limit=50)
                if f.timestamp < threshold
            ]
            goals = []
            if len(stale) >= 5:
                goals.append(Goal(
                    goal_id="knowledge-stale",
                    title=f"Refresh {len(stale)} stale shared knowledge facts",
                    description=f"{len(stale)} facts in shared pool are older than 7 days. "
                                 "Consider re-validating or removing them.",
                    goal_type=GoalType.KNOWLEDGE_STALE,
                    priority=Priority.LOW,
                    estimated_impact="Keeps shared knowledge fresh and relevant",
                    auto_executable=False,
                    suggested_action="Run re-validation pipeline on stale facts",
                    source_evidence={"stale_count": len(stale), "threshold_days": 7},
                ))
            return goals
        except Exception as e:
            logger.debug("knowledge staleness scan skipped: %s", e)
            return []

    def _scan_exploration_gaps(self) -> List[Goal]:
        """Scan for error types that are active but have untried strategies."""
        try:
            from core.harness.optimization.strategy_tracker import get_strategy_tracker
            tracker = get_strategy_tracker()
            goals = []
            for (error_type, strategy), rec in tracker._records.items():
                if rec.attempts >= 5 and rec.success_rate > 0.7:
                    # This strategy works well — check if there are unexplored alternatives
                    explore = tracker.explore_strategy(error_type)
                    if explore:
                        goals.append(Goal(
                            goal_id=f"explore-{error_type}-{explore}",
                            title=f"Explore alternative: '{explore}' for '{error_type}'",
                            description=f"Current best strategy has {rec.success_rate:.0%} "
                                         f"success. Untried '{explore}' may be even better.",
                            goal_type=GoalType.EXPLORATION_GAP,
                            priority=Priority.LOW,
                            estimated_impact="Potentially improves healing by discovering better strategies",
                            auto_executable=True,
                            suggested_action=f"Allow tracker to try '{explore}' next time",
                            source_evidence={
                                "error_type": error_type,
                                "current_best": strategy,
                                "untried": explore,
                            },
                        ))
            return goals
        except Exception as e:
            logger.debug("exploration gap scan skipped: %s", e)
            return []

    def stats(self) -> Dict[str, Any]:
        """Generate summary stats."""
        goals = self.generate()
        return {
            "total_goals": len(goals),
            "by_type": {t.value: sum(1 for g in goals if g.goal_type.value == t.value) for t in GoalType},
            "by_priority": {p.name: sum(1 for g in goals if g.priority == p) for p in Priority},
            "auto_executable": sum(1 for g in goals if g.auto_executable),
            "top_goal": goals[0].to_dict() if goals else None,
        }


# ── Process-wide singleton ──

_generator: Optional[GoalGenerator] = None


def get_goal_generator() -> GoalGenerator:
    global _generator
    if _generator is None:
        _generator = GoalGenerator()
    return _generator
