"""
AI Platform - Core Layer
"""

__version__ = "1.0.0"

from .exceptions import (
    CoreError,
    AgentError,
    AgentInitializationError,
    AgentExecutionError,
    AgentTimeoutError,
    AgentStateError,
    MemoryError,
    MemoryStoreError,
    MemoryRetrieveError,
    MemoryOverflowError,
    ModelError,
    ModelConnectionError,
    ModelTimeoutError,
    ModelRateLimitError,
    ModelResponseError,
    SkillError,
    SkillNotFoundError,
    SkillExecutionError,
    SkillTimeoutError,
    ToolError,
    ToolNotFoundError,
    ToolExecutionError,
    ToolTimeoutError,
    KnowledgeError,
    KnowledgeIndexError,
    KnowledgeRetrieveError,
    OrchestrationError,
    WorkflowError,
    WorkflowTimeoutError,
    StepExecutionError,
)

from .services import (
    PromptService,
    PromptTemplate,
    ModelService,
    ModelConfig,
    TraceService,
    TraceContext,
    ContextService,
    SessionContext,
)

__all__ = [
    "__version__",
    # Exceptions
    "CoreError",
    "AgentError",
    "AgentInitializationError",
    "AgentExecutionError",
    "AgentTimeoutError",
    "AgentStateError",
    "MemoryError",
    "MemoryStoreError",
    "MemoryRetrieveError",
    "MemoryOverflowError",
    "ModelError",
    "ModelConnectionError",
    "ModelTimeoutError",
    "ModelRateLimitError",
    "ModelResponseError",
    "SkillError",
    "SkillNotFoundError",
    "SkillExecutionError",
    "SkillTimeoutError",
    "ToolError",
    "ToolNotFoundError",
    "ToolExecutionError",
    "ToolTimeoutError",
    "KnowledgeError",
    "KnowledgeIndexError",
    "KnowledgeRetrieveError",
    "OrchestrationError",
    "WorkflowError",
    "WorkflowTimeoutError",
    "StepExecutionError",
    # Services
    "PromptService",
    "PromptTemplate",
    "ModelService",
    "ModelConfig",
    "TraceService",
    "TraceContext",
    "ContextService",
    "SessionContext",
]