/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3B82F6',
          hover: '#2563EB',
          active: '#1D4ED8',
          light: '#1C2128',
          border: '#388BFD33',
        },
        success: {
          DEFAULT: '#10B981',
          hover: '#059669',
          active: '#047857',
          light: '#0D1117',
          border: '#23863633',
        },
        warning: {
          DEFAULT: '#F59E0B',
          hover: '#D97706',
          active: '#B45309',
          light: '#0D1117',
          border: '#9E6A0333',
        },
        error: {
          DEFAULT: '#EF4444',
          hover: '#DC2626',
          active: '#B91C1C',
          light: '#0D1117',
          border: '#F8514966',
        },
        dark: {
          bg: '#0D1117',
          card: '#161B22',
          hover: '#1C2128',
          border: '#30363D',
        },
      },
      fontFamily: {
        sans: ["'Geist Variable'", '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'Roboto', "'Helvetica Neue'", 'Arial', 'sans-serif'],
        mono: ["'JetBrains Mono'", "'Fira Code'", 'Consolas', 'monospace'],
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0, 0, 0, 0.3)',
        sm: '0 1px 3px rgba(0, 0, 0, 0.4), 0 1px 2px rgba(0, 0, 0, 0.3)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.4), 0 2px 4px -2px rgba(0, 0, 0, 0.3)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.4), 0 4px 6px -4px rgba(0, 0, 0, 0.3)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 8px 10px -6px rgba(0, 0, 0, 0.3)',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-dark-bg',
    'bg-dark-card',
    'bg-dark-hover',
    'border-dark-border',
    'text-gray-50',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'bg-primary',
    'bg-primary-light',
    'bg-success-light',
    'bg-warning-light',
    'bg-error-light',
    'text-primary',
    'text-success',
    'text-warning',
    'text-error',
    'border-gray-300',
    'border-gray-400',
    'border-gray-500',
    'border-gray-600',
    'border-gray-700',
    'border-gray-800',
    'rounded-lg',
    'rounded-xl',
    'rounded-full',
    'shadow-sm',
    'shadow-md',
    'flex',
    'grid',
    'block',
    'hidden',
    'p-4',
    'px-4',
    'py-2',
    'space-y-4',
  ],
}
